//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSystem2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBooking
    {
        public FlightBooking()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int bookingID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> flightID { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
